apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # replica set labels
  labels:
    component: mongodb
    project: roboshop
    tier: backend
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: backend
  # This is pod definition
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: backend
    spec:
      containers:
      - name: mongodb
        image: iamrams/mongodb:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: backend
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: backend
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port